config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :microposts
  resources :users

  root to:'rooms#index'
  match '/manifest.webapp', to: 'static_pages#manifest',  via: 'get', defaults: { format: "json" }
  match '/manifest2.webapp', to: 'static_pages#manifest',  via: 'get', defaults: { format: "json" }
  match '/install', to: 'static_pages#install', via: 'get', defaults: { format: "html" }

end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :users
	has_many :microposts, dependent: :destroy
	validates :room_name, uniqueness: true, length: {maximum: 100}, presence: true
end
 

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :set_room, only: [:show, :edit, :update, :destroy]

	# GET /rooms
	# GET /rooms.json
	def index
		@rooms = Room.order(updated_at: :desc)
		respond_to do |format|
			format.html
			format.json { render json: @rooms }
		end
	end

	# GET /rooms/1
	# GET /rooms/1.json
	def show
		respond_to do |format|
			format.html 
			format.json do
				@uuid = params[:uuid]
				@user = User.find_by(uuid: @uuid)
				@donno = params[:donno]
				#@wow = params[:wow]
				logger.debug "テスト123020#{@donno}"
				if @donno == "true"
					@user.donno = true
				else
					@user.donno = false
				end
				#@user.wow = @wow
				if @room.id != @user.room_id
					@user.room_id=@room.id
				end
				@user.touch
				@user.save

				@last = params[:last].to_i
				conditions = @room.microposts.arel_table
				@microposts = @room.microposts.where(conditions[:id].gt(@last))
				#@microposts = @room.microposts.offset(@last)
				@users = @room.users.where(updated_at: (15.seconds.ago)..(Time.now))
				if @room.updated_at < 1.second.ago
					@donno_rate = 0
					@users.each do |user|
						if user.donno == true
							@donno_rate += 1
						end
					end
					@donno_rate = @donno_rate.to_f/@users.count

					@wow_users = @room.users.where(wow_updated: (10.seconds.ago)..(Time.now))
					@wow_rate = 0
					@wow = 0
					@wow_users.each do |user|
						@wow += user.wow
					end
					@wow_rate = @wow_users.count != 0 ? @wow.to_f/@users.count : 0

					@room.donno = @donno_rate
					@room.wow = @wow_rate 
					@room.touch
					@room.save
				else
					@donno_rate = Room.find(params[:id]).donno
					@wow_rate = Room.find(params[:id]).wow
				end
			end
		end
	end

	# GET /rooms/new
	def new
		@room = Room.new
	end

	# GET /rooms/1/edit
	def edit
	end

	# POST /rooms
	# POST /rooms.json
	def create
		@room = Room.new(room_params) 

		respond_to do |format|
			if @room.save
				format.html { redirect_to @room, notice: 'Room was successfully created.' }
				format.json { render json: @room, status: :created}
			else
				format.html { render :new }
				format.json { render json: @room.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /rooms/1
	# PATCH/PUT /rooms/1.json
	def update
		respond_to do |format|
			if @room.update(room_params)
				format.html { redirect_to @room, notice: 'Room was successfully updated.' }
				format.json { render :show, status: :ok, location: @room }
			else
				format.html { render :edit }
				format.json { render json: @room.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /rooms/1
	# DELETE /rooms/1.json
	def destroy
		@room.destroy
		respond_to do |format|
			format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_room
			@room = Room.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def room_params
			params.require(:room).permit(:room_name)
		end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_name, 'ルーム名' %><br>
    <%= f.text_field :room_name %>
  </div>
	<br>

  <div class="actions">
    <%= f.submit '作成' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<head>
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
</head>

<div class="container-fluid">
<p id="notice"><%= notice %></p>

<h1>ルーム一覧</h1>

<table>
  <thead>
    <tr>
      <th>ルーム名</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.room_name, room %></td>
        <!-- <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいルームを作る', new_room_path %>
</div>

app/views/rooms/new.html.erb
<div class="container-fluid">
<h1>ルーム作成</h1>

<%= render 'form' %>

<%= link_to '戻る', rooms_path %>
</div>